server:
  port: ${PORT:5154}
  context-path: /uaa

spring:
  application:
    name: accounts-auth
  datasource:
    url: jdbc:mysql://localhost:3306/smartlab
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    schema: classpath:/script/schema.sql
#    data: classpath:/script/data.sql

logging:
  level:
    org.springframework.security: DEBUG
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:5154/uaa/oauth/token
      userAuthorizationUri: http://localhost:5154/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:5154/uaa/user