server:
  port: ${PORT:8732}

spring:
  application:
    name: edge-service

  datasource:
    url: jdbc:mysql://localhost:3306/smartlab_coordinator?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: docker

  datasource:
      url: jdbc:mysql://db:3306/db?useSSL=false
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true