server:
  port: ${PORT:8765}

spring:
  application:
    name: gateway-service
#  datasource:
#    url: jdbc:mysql://192.168.99.100:33306/oath2?useSSL=false
#    username: default
#    password: default

logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE

zuul:
  routes:
    auth:
      path: /uaa/**
      url: http://localhost:5154
      sensitiveHeaders:
      strip-prefix: false
      serviceId: auth-service
    account:
      path: /account/**
      sensitiveHeaders:
      serviceId: account-service

security:
  oauth2:
    sso:
      loginPath: /uaa/login
    client:
      accessTokenUri: http://localhost:8765/uaa/oauth/token
      userAuthorizationUri: http://localhos:8765/uaa/oauth/authorize
      clientId: acme
      clientSecret: secret
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://localhost:5154/user
      preferTokenInfo: false
  sessions: ALWAYS