server:
  port: ${PORT:5153}

spring:
  application:
    name: accounts-service
  datasource:
    url: jdbc:mysql://localhost:3306/smartlab
    username: root
    password: root

logging:
  level:
    org.springframework.security: TRACE

security:
  user:
    password: none
  oauth2:
    client:
      client-id: account-service
      client-secret: secret
      scope: read
      access-token-uri: http://localhost:5154/oauth/token
      user-authorization-uri: http://localhost:5154/oauth/authorize
    resource:
      token-info-uri: http://localhost:5154/oauth/check_token